# Generated by Django 3.0.8 on 2020-08-15 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blogid', models.AutoField(primary_key=True, serialize=False)),
                ('blogname', models.CharField(max_length=200)),
                ('blogtext', models.CharField(blank=True, max_length=200)),
                ('likeno', models.IntegerField(blank=True)),
                ('dislikeno', models.IntegerField(blank=True)),
                ('comment', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('likeid', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.IntegerField(blank=True)),
                ('dislike', models.IntegerField(blank=True)),
                ('blogid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogsys.Blogs')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogsys.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(blank=True, max_length=64)),
                ('blogid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogsys.Blogs')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogsys.User')),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='creatorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogsys.User'),
        ),
    ]
