# Generated by Django 3.0.8 on 2020-08-17 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='comment',
            new_name='commentno',
        ),
        migrations.AddField(
            model_name='blogs',
            name='postdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='creatorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blog', to='blogsys.User'),
        ),
    ]
