# Generated by Django 3.0.8 on 2020-08-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsys', '0002_auto_20200817_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='postedon',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
