# Generated by Django 3.0.8 on 2020-08-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsys', '0003_auto_20200817_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='commentno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='dislikeno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='likeno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='postdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='postedon',
            field=models.DateField(),
        ),
    ]
