# Generated by Django 3.0.8 on 2020-08-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsys', '0004_auto_20200817_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blogtext',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='comments',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
