# Generated by Django 3.0.8 on 2020-08-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsys', '0007_auto_20200818_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blogimage',
            field=models.ImageField(height_field=300, null=True, upload_to=None, width_field=750),
        ),
    ]
