# Generated by Django 3.0.8 on 2020-08-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsys', '0008_blogs_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blogimage',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
