# Generated by Django 3.0.8 on 2020-08-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsys', '0012_auto_20200820_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikes',
            name='dislike',
        ),
        migrations.AlterField(
            model_name='userlikes',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
